title: Oracle Mestre Chalita
description: Leitura holística com 5 pilares - Astrologia, Numerologia, Kabbalah, The Pattern, Tiferet
theme: jekyll-theme-minimal
logo: assets/logo.svg
github_repository: borgex21/oracle-mestre-chalita
show_downloads: false
